version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    command: >
      /sbin/init &&
      systemctl restart sshd
    privileged: true
  client:
    build:
      context: .
      dockerfile: ./Dockerfile.client
    command: /sbin/init
